$(OBJ_DIR)/mlegs_base.o : $(MODULE_DIR)/mlegs_base.f90 
$(OBJ_DIR)/mlegs_misc.o : $(MODULE_DIR)/mlegs_misc.f90 $(OBJ_DIR)/mlegs_base.o 
$(OBJ_DIR)/mlegs_misc_time.o : $(SUBMODULE_DIR)/mlegs_misc_time.f90 $(OBJ_DIR)/mlegs_misc.o 
