PROGRAM MPI_SCHEDULER
!=======================================================================
! [USAGE]: 
! Faster Version: the bar term is calculated once for each wavenumber
! Modified to include M=0 mode
! Check resolved or not using EIGRES
! 
! FIND EIGENVALUES AND EIGENVECTORS OF THE LINEARIZED N-S EQUATIONS
! EXPRESSED IN A POLOIDAL-TOROLIDALLY DECOMPOSED FORM
! OPERATOR H CORRESPONDS TO EIGENVECTOR: [PSI,DEL2CHI]^T
! USE VPROD_PFF
! [UPDATES]:
! LAST UPDATE ON DEC 3, 2020
!=======================================================================
USE omp_lib
USE MPI
USE IFPORT
USE MOD_MISC

IMPLICIT NONE
INTEGER:: MPI_GLB_PROCS, MPI_GLB_RANK, IERR, MPI_REC_ID
INTEGER:: II, JJ, KK, JOBID, JOBEND, SLEEP_DUR, RANDSEED
INTEGER:: FID, IS, STATUS(MPI_STATUS_SIZE), REQUEST, ST
LOGICAL:: WORKER, ISDONE, ISRANK
REAL:: SLEEP_TIME

CHARACTER(LEN=72):: FILENAME
CHARACTER(LEN=300):: PRTSTR
CHARACTER(:),ALLOCATABLE:: LONGSTR

CALL MPI_INIT(IERR)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD, MPI_GLB_PROCS, IERR)
CALL MPI_COMM_RANK(MPI_COMM_WORLD, MPI_GLB_RANK, IERR)
IF (MPI_GLB_RANK.EQ.0) THEN
    WRITE(*,*) 'PROGRAM STARTED'
    CALL PRINT_REAL_TIME()   ! @ MOD_MISC
ENDIF

CALL MPI_FILE_OPEN(MPI_COMM_WORLD, 'TEST.LOG', MPI_MODE_WRONLY + MPI_MODE_CREATE, MPI_INFO_NULL, FID, IS)
IF (IS.NE.0) WRITE(*,*) 'RANK#',ITOA4(MPI_GLB_RANK),'ERROR open TEST.LOG'
CALL MPI_FILE_SET_ATOMICITY(FID, .TRUE., IERR)

! MANAGER:
IF (MPI_GLB_RANK.EQ.0) THEN

    ! INITIALIZATION
    JOBID = 0
    JOBEND = 20
    ISDONE = .FALSE.
    SLEEP_DUR = 10

    DO WHILE (.NOT.(ISDONE))
        
        ! Receive from ANY available source
        ! MPI_RECV(BUF, COUNT, DATATYPE, SOURCE, TAG, COMM, STATUS, IERROR)
        CALL MPI_RECV(WORKER,1,MPI_LOGICAL,MPI_ANY_SOURCE,MPI_ANY_TAG,MPI_COMM_WORLD,STATUS,IERR)
        MPI_REC_ID = STATUS(MPI_SOURCE)

        IF (WORKER) THEN
            JOBID = JOBID + 1
            SLEEP_TIME = RANDOM(0)*SLEEP_DUR
            ! MPI_SEND(BUF, COUNT, DATATYPE, DEST, TAG, COMM, IERROR)
            CALL MPI_SEND(JOBID,1,MPI_INTEGER,MPI_REC_ID,1,MPI_COMM_WORLD,IERR)
            CALL MPI_SEND(SLEEP_TIME,1,MPI_DOUBLE,MPI_REC_ID,2,MPI_COMM_WORLD,IERR)
            ! WRITE(*,*) 'RANK#',ITOA4(MPI_GLB_RANK),' SET JOB#',ITOA4(JOBID),' TO RANK#', ITOA4(MPI_REC_ID)
        ELSE
            CYCLE
        ENDIF

        IF (JOBID.GE.JOBEND) ISDONE = .TRUE.

    ENDDO

    ! NOTIFY ALL PROCS
    DO II = 1,MPI_GLB_PROCS-1
        CALL MPI_ISEND(-1,1,MPI_INTEGER,II,1,MPI_COMM_WORLD,REQUEST,IERR)
    ENDDO
    WRITE(*,*) 'RANK#',ITOA4(MPI_GLB_RANK),' - FINISHED'

! WORKER:
ELSE

    JOBID = 0
    ! ISRANK = .FALSE.; IF (MPI_GLB_RANK.EQ.2) ISRANK = .TRUE.
    ISRANK = .TRUE.

    DO WHILE (JOBID.NE.-1) 

        ! Tell manager the proc is available
        WORKER = .TRUE.
        CALL MPI_SEND(WORKER,1,MPI_LOGICAL,0,1,MPI_COMM_WORLD,IERR)

        ! Receive the JOBID
        CALL MPI_RECV(JOBID,1,MPI_INTEGER,0,1,MPI_COMM_WORLD,STATUS,IERR)
        IF (JOBID.EQ.-1) EXIT
        CALL MPI_RECV(SLEEP_TIME,1,MPI_DOUBLE,0,2,MPI_COMM_WORLD,STATUS,IERR)
                
        ! Do work
        IF (ISRANK) WRITE(*,*) 'RANK#',ITOA4(MPI_GLB_RANK),' GOT JOB#',ITOA4(JOBID),' SLEEP FOR ',ITOA4(NINT(SLEEP_TIME)),' sec'
        CALL SLEEP(NINT(SLEEP_TIME))

        ! Update log
        WRITE(PRTSTR,*) 'RANK#',ITOA4(MPI_GLB_RANK),' - JOBID#',ITOA4(JOBID)
        LONGSTR = TRIM(PRTSTR) // NEW_LINE('A')
        CALL MPI_FILE_WRITE_SHARED(FID, TRIM(LONGSTR), LEN(TRIM(LONGSTR)) , MPI_CHAR, ST, IERR)

    ENDDO

    WRITE(*,*) 'RANK#',ITOA4(MPI_GLB_RANK),' - FINISHED'


ENDIF

CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
CALL MPI_FILE_CLOSE(FID,IERR)

IF (MPI_GLB_RANK.EQ.0) THEN    
    WRITE(*,*) ''
    WRITE(*,*) 'PROGRAM FINISHED'
    CALL PRINT_REAL_TIME()  ! @ MOD_MISC
ENDIF
CALL MPI_FINALIZE(IERR)

END PROGRAM MPI_SCHEDULER
!=======================================================================
