title: 'MLegS'
description: Modernized and Parallelized Mapped Legendre Spectral Method Code
theme: just-the-docs

url: https://ucbcfd.github.io/MLegS

color_scheme: dark

aux_links:
  "Powered by Just the Docs":
    - "//github.com/just-the-docs/just-the-docs"

aux_links_new_tab: false

nav_external_links:
  - title: MLegS Code Repository
    url: "https://github.com/ucbcfd/mlegs"
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false

plugins:
  - jekyll-default-layout
  - jekyll-sitemap

back_to_top: true
back_to_top_text: "Back to top"

favicon_ico: "/assets/images/favicon.ico"