source 'https://rubygems.org'

gem "jekyll", "~> 4.3.4" # installed by `gem jekyll`

gem "just-the-docs", "0.10.0" # pinned to the current release

gem "jekyll-default-layout"
gem "jekyll-sitemap", group: :jekyll_plugins
